### ISSUE TITLE
IDE temp files

### ISSUE THREAD

**Issue by oligriffiths** [toranb/ember-cli-hot-loader#42]
Hey

I've noticed that occasionally the page refreshes due to IDE temp file changed, for example:

```
file deleted components/my-component/component.js___jb_tmp___
file deleted components/my-component/component.js___jb_old___
file changed components/my-component/component.js
```

I use a jetbrains IDE that uses temp files sometimes, and these cause the app to reboot. Can we make the excluded files configurable or include those temp extension patterns?

Thanks

**Comment by oligriffiths** [comment]
I realise that this is an ember cli issue, so if you have any advice on how to handle this there, im all ears.

**Comment by toranb** [comment]
@oligriffiths what happens here when you just install fresh (without the hot loader addon)? Does it also pick up these changes and randomly "refresh" because of the IDE?

I'm curious if you could just ask watchman/or ember-cli to exclude them from the change detection. Assuming you've looked into that already ....

@MiguelMadero is this the spot that we could possibly alter something to avoid a "refresh" like @oligriffiths mentions here?

https://github.com/toranb/ember-cli-hot-loader/blob/master/lib/hot-reloader.js#L5-L6

**Comment by oligriffiths** [comment]
I believe this to be a cli issue to be a hot reload issue. Il keep looking into it.

**Comment by MiguelMadero** [comment]
I'm not sure we should deal with it at this level.... Quite likely there is a weird pattern in CLI, node-watcher or watchman that is looking at those files. 

@oligriffiths are you using watchman or node-watcher? you can add --watcher to be explicit when running `ember serve` or similar commands. For example: 

```
ember serve --watcher=node
ember serve --watcher=watchman
```

**Comment by oligriffiths** [comment]
@MiguelMadero Using watchman, but you're right it should be handled at the CLI level as they shouldn't even be counted.
